name: deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: deploy
    runs-on: ubuntu-24.04
    if: false # Disabling this given that we are doing deployments with Cloudflare pages now
    steps:
      - uses: actions/checkout@v1 # necessary to fetch all files from repo, including actions
      - uses: ./.github/actions/build-dist-site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}